### ISSUE TITLE
Unable to Download Fragment file from Provided Link

### ISSUE THREAD

**Issue by pondandmoon** [ejarmand/comparative_epigenomic_motor_cortex#4]
Hi @ejarmand 

Thank you for your excellent work on the mammalian neocortex. I’ve found your research to be incredibly insightful. I am reaching out because I attempted to download the Fragment file using the link you previously provided. Unfortunately, it seems that the link is no longer working, and I’m unable to access the data. Could you please confirm whether the link has expired? If so, would it be possible to provide an updated method for downloading the data? Thank you in advance for your help. I look forward to your response.

**Comment by ejarmand** [comment]
Hi Pondandmoon, Apologies this took a while, I've updated the links on the document, they should work until October.

Best,

Ethan

**Comment by pondandmoon** [comment]
Hi @ejarmand 
Thanks for letting me know about the link repair. I'll check back in October.

**Comment by ejarmand** [comment]
Hi @pondandmoon for a final update the fragment files are now permanently hosted on the 4DN data portal:

[https://data.4dnucleome.org/publications/8d4e8d7c-b98f-4857-a4c1-274dfc39817a/](https://data.4dnucleome.org/publications/8d4e8d7c-b98f-4857-a4c1-274dfc39817a/)
